# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KYWebo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # OC
    pod 'YYKit',  '~> 1.0.9'

    pod 'JPFPSStatus',  '~> 0.1'

    # Swift
    pod 'SnapKit', '~> 3.0.2'

end

