# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KYChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KYChat
  pod 'SnapKit', '~> 3.2.0'
  pod 'Alamofire','~> 4.0.0'
  pod 'SwiftyJSON', '3.1.3'
  pod 'Kingfisher', '3.5.2'
  pod 'ObjectMapper', '2.2.5'
  
  pod 'Proposer', '1.1.0'
  pod 'PermissionScope', '1.1.1'
  pod 'Then', '2.1.0'
  pod 'APIKit', '3.1.1'
  pod 'BSImagePicker', '2.5.1'
  pod 'Reusable'

  # OC
  pod 'MBProgressHUD', '1.0.0'
  pod 'KVOController', '1.2.0'
  pod 'YYText', '1.0.7'
  pod 'FMDB', '2.6.2'

  target 'KYChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KYChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
