# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KYAppBase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KYAppBase
  # Swift
    pod 'SnapKit', '~> 3.0.2'

  target 'KYAppBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KYAppBaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
